config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/users#index'
 
  resources :users
  resources :bid_logs
  namespace :admin do
    resources :users do
      get 'delete_avatar'
      get 'list_team_players'
      post 'close_bid'
    end

    resources :matches do
      collection do
        get 'points_table'
      end
    end

    resources :innings do
      get 'start_innings'
      post 'proceed_innings'
      post 'create_ball_details'
      post 'create_over'
      get 'switch_strike'
      get 'scoreboard'
    end
  end
  namespace :team_owner do
    resources :users do
      get 'list_team_players'
      get 'delete_avatar'
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/inning.rb
class Inning < ActiveRecord::Base
	belongs_to :match
	belongs_to :team
	has_many :overs
	has_many :wickets
end

app/controllers/admin/innings_controller.rb
class Admin::InningsController < ApplicationController
	def show
		@inning = Inning.where(id: params[:id]).first
		@batsmen = @inning.team.users.where(is_batting: true)
		@striker = @batsmen.where(is_on_strike:true).first
		@non_striker = @batsmen.where(is_on_strike:false).first
		@bowler = Team.where(id: @inning.opponent_id).first.users.where(is_bowling: true).first
		@opponents = Team.where(id: @inning.opponent_id).first.users
		@opponent_inning = Inning.where(team_id: @inning.opponent_id, match_id: @inning.match_id).first
		@over = @inning.overs.last || Over.create(inning_id: @inning.id, bowler_id: @bowler.id, status: 'NEW')
	end

	def start_innings
		@inning = Inning.where(id: params[:inning_id]).first
		@batsmen = @inning.team.users
		@active_batsmen = @inning.team.users.where(is_batting: true)
		@bowlers = Team.where(id: @inning.opponent_id).first.users
		@active_bowler = Team.where(id: @inning.opponent_id).first.users.where(is_bowling: true).first
	end

	def create_ball_details
		@inning = Inning.where(id: params[:inning_id]).first
		@over = Over.where(id: params[:over_id]).first
		legitimacy = params[:extra_type].blank?
		@ball = Ball.create(over_id: @over.id, batsman_id: params[:batsman_id],
								runs_scored: params[:runs_scored], result: params[:result],
								extra_type: params[:extra_type], extra: params[:extra_runs],
								is_legitimate: legitimacy)
		if legitimacy
			@inning.overs_played = @inning.overs_played.to_f + 0.1
		end
		@inning.runs_scored = @inning.runs_scored.to_i + params[:runs_scored].to_i + params[:extra_runs].to_i
		@inning.save
		@over.update_status
		change_strike
		create_wickets
		update_innings
		if @inning.status == 'COMPLETED'
			redirect_to admin_match_path(@inning.match)
		elsif params[:wicket_type].present?
			redirect_to admin_inning_start_innings_path(@inning)
		else
			redirect_to admin_inning_path(@inning)
		end
	end

	def create_over
		inning = Inning.where(id: params[:inning_id]).first
		bowler = User.where(id: params[:bowler_id]).first
		over_count = inning.overs.count
		Over.create(inning_id: params[:inning_id], bowler_id: params[:bowler_id], status: 'NEW', over_number: over_count+1)
		bowler.update_attributes(is_bowling: true)
		redirect_to admin_inning_path(inning)
	end

	def proceed_innings
		inning = Inning.where(id: params[:inning_id]).first
		batsman_1 = User.where(id: params[:batsman_1]).first
		batsman_2 = User.where(id: params[:batsman_2]).first
		bowler = User.where(id: params[:bowler_id]).first
		if inning.status == 'NEW'
			Over.create(inning_id: params[:inning_id], bowler_id: params[:bowler_id], status: 'NEW', over_number: 1)
			batsman_1.update_attributes(is_batting:true, is_on_strike:true) if batsman_1.present?
			batsman_2.update_attributes(is_batting:true, is_on_strike:false) if batsman_2.present?
		else
			other_batsman = User.where(team_id: inning.team_id, is_batting:true).first
			batsman_1.update_attributes(is_batting:true) if batsman_1.present?
			batsman_2.update_attributes(is_batting:true, is_on_strike: !other_batsman.is_on_strike) if batsman_2.present?		
		end		
		bowler.update_attributes(is_bowling: true) if bowler.present?
		inning.update_attributes(status: 'ONGOING')
		inning.match.update_attributes(status: 'ONGOING')
		redirect_to admin_inning_path(inning)
	end

	def change_strike
		if [1,3].include?(params[:runs_scored].to_i) || 
			(['Leg Bye', 'Bye'].include?(params[:extra_type]) && [1,3].include?(params[:extra_runs].to_i)) ||
			(@over.over_ended?)
			striker = User.where(id: params[:batsman_id]).first
			non_striker = User.where(id: params[:non_striker_id]).first
			striker.update_attributes(is_on_strike: false)
			non_striker.update_attributes(is_on_strike: true)
		end
	end

	def update_innings
		@opponent_inning = Inning.where(team_id: @inning.opponent_id, match_id: @inning.match_id).first
		if @inning.status == 'ONGOING' && ((@over.over_number == 8 && @over.over_ended?) ||
				@inning.wickets.count == 10 ||
				(@opponent_inning.status == 'COMPLETED' && @inning.runs_scored > @opponent_inning.runs_scored))
			@inning.update_attributes(status: 'COMPLETED')
			match = @inning.match
			User.where(team_id: @inning.team_id, is_batting: true).update_all(is_batting:false, is_on_strike:false)
			both_innings = match.innings
			if both_innings.map(&:status) == ['COMPLETED','COMPLETED']
				if both_innings.first.runs_scored > both_innings.last.runs_scored
					match.update_attributes(winner_id: both_innings.first.team_id, status:'COMPLETED')
				elsif both_innings.first.runs_scored < both_innings.last.runs_scored
					match.update_attributes(winner_id: both_innings.last.team_id, status:'COMPLETED')
				end
			end
		end
	end

	def create_wickets
		if params[:wicket_type].present?
			wicket = Wicket.create(batsman_id: params[:wicket_batsman], wicket_type: params[:wicket_type],
										bowler_id: @over.bowler_id, ball_id: @ball.id, inning_id: @inning.id,
										wicket_partner_id: params[:wicket_partner])
			@ball.update_attributes(wicket_id: wicket.id)
			batsman = User.where(id: params[:wicket_batsman]).first
			strike_retain = batsman.is_on_strike
			batsman.update_attributes(is_batting: false, is_on_strike:false)
			unless strike_retain
				other_batsman = User.where(team_id: @inning.team_id, is_batting:true).first
				other_batsman.update_attributes(is_on_strike: true) if other_batsman.present?
			end
			@inning.update_attributes(status: 'COMPLETED') if @inning.wickets.count == 10
		end
	end

	def switch_strike
		inning = Inning.where(id: params[:inning_id]).first
		batsmen = User.where(team_id: inning.team_id, is_batting:true)
		batsmen.first.update_attributes(is_on_strike: !batsmen.first.is_on_strike)
		batsmen.last.update_attributes(is_on_strike: !batsmen.last.is_on_strike)
		redirect_to admin_inning_path(inning)
	end

	def scoreboard
		@inning = Inning.where(id: params[:inning_id]).first
		@batsmen = User.where(team_id: @inning.team_id)
		@batsmen = @batsmen.sort_by{|b| b.crease_arrival_order(@inning.id)}
	end
end

app/helpers/admin/innings_helper.rb
module Admin::InningsHelper

	def get_result_master_list
		['1 Run',
			'2 Runs',
			'3 Runs',
			'4 Runs',
			'5 Runs',
			'6 Runs',
			'Wicket',
			'Extra',
			'Dead']
	end

	def get_wicket_master_list
		[nil,
			'Bowled',
			'Caught',
			'LBW',
			'Stumped',
			'Run Out',
			'Hit Wicket',
			'Hit Out']
	end

	def get_extra_master_list
		[nil,
			'Wide Ball',
			'No Ball',
			'Bye',
			'Leg Bye']
	end
end

app/views/admin/innings/scoreboard.html.erb
<h1 align="center">SCOREBOARD</h1>
<table class="flat-table flat-table-1" align="center" >
  <tr>
    <th>Batsman</th>
    <th/>
    <th>Runs</th>
    <th>Balls</th>
    <th>4s</th>
    <th>6s</th>
    <th>Strike Rate</th>
  </tr>
  <% @batsmen.each do |batsman| %>
    <% details = batsman.calculate_runs(@inning.id) %>
    <tr>
      <td><%= batsman.get_full_name %></td>
      <td><%= batsman.get_wicket_info(@inning.id, details[1]) %></td>
      <td><%= details[0] || '--' %></td>
      <td><%= details[1] || '--' %></td>
      <td><%= details[2] || '--' %></td>
      <td><%= details[3] || '--' %></td>
      <td><%= ((details[0].to_f / details[1].to_f) * 100).round(2) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', admin_match_path(@inning.match), :class => 'myButton' %>

app/views/admin/innings/show.html.erb
<table class="form-style-10">
  <h1 id="label" align="center"><%= @inning.team.name %></h1>
  <h1 id="label" align="center"><%= @inning.runs_scored %>/<%= @inning.wickets.count %></h1>
  <h1 id="label" align="center"><%= @inning.overs_played %> overs</h1>
  <h3 id="label" align="center"><%= "#{@opponent_inning.team.name}:#{@opponent_inning.runs_scored}/#{@opponent_inning.wickets.count}" %> overs</h1>
  <div align="center"><%= link_to "Scoreboard", admin_inning_scoreboard_path(@inning), :class => 'myButton' %>
  </div>
  <tr><th align="left">Batting:</th>
      <td>Runs</td>
      <td>Balls</td>
      <td>4s</td>
      <td>6s</td>
      <td>Strike Rate</td>
  </tr>
  <tr>
    <% striker_details = @striker.calculate_runs(@inning.id) %>
    <td align="left" style="font-size:x-large"><strong><%= @striker.get_full_name %>*</strong></td>
    <th><%= striker_details[0] || 0 %></th>
    <th><%= striker_details[1] || 0 %></th>
    <th><%= striker_details[2] || 0 %></th>
    <th><%= striker_details[3] || 0 %></th>
    <th><%= ((striker_details[0].to_f / striker_details[1].to_f) * 100).round(2) %></th>
  </tr>
  <tr>
    <% non_striker_details = @non_striker.calculate_runs(@inning.id) %>
    <td align="left" style="font-size:x-large"><strong><%= @non_striker.get_full_name %></strong></td>
    <th><%= non_striker_details[0] || 0 %></th>
    <th><%= non_striker_details[1] || 0 %></th>
    <th><%= non_striker_details[2] || 0 %></th>
    <th><%= non_striker_details[3] || 0 %></th>
    <th><%= ((non_striker_details[0].to_f / non_striker_details[1].to_f) * 100).round(2) %></th>
  </tr>
  <tr>
    <td colspan="6" align="left"><% 195.times do %>-<%end%></td>
  </tr>
  <tr><th align="left">Bowler:</td>
      <th align="right">Overs</td>
      <th align="right">Wickets</td>
      <th align="right">Runs</td>
      <th align="right">Economy</td></tr>
  
  <tr>
    <td align="left" style="font-size:x-large"><strong><%= @bowler.try(:get_full_name) || '--' %></strong></td>
    <% if @bowler.present? %>
      <% bowler_details = @bowler.get_bowling_details(@inning.id) %>
      <th><%= bowler_details[0] || 0 %></th>
      <th><%= bowler_details[1] || 0 %></th>
      <th><%= bowler_details[2] || 0 %></th>
      <th><%= (bowler_details[0].to_f / bowler_details[2].to_f).round(2) || 0 %></th>
    <% end %>
  </tr>
</table>

<% if @over.status == 'COMPLETED' %>
  <table class="form-style-10">
    <%= form_tag admin_inning_create_over_path(@inning) do %>
      <tr>
        <th colspan="8" align="center" style="font-size:x-large">Start a new over</th>
      </tr>
      <tr>
        <th>Select Bowler</th>
        <td><%= select_tag 'bowler_id', options_from_collection_for_select(@opponents, "id", "get_full_name") %></td>
        <td align="center"><%= submit_tag 'Submit' %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <table class="form-style-10">
    <%= form_tag admin_inning_create_ball_details_path(@inning) do %>
      <%= hidden_field_tag :over_id, @over.id %>
      <%= hidden_field_tag :batsman_id, @striker.id %>
      <%= hidden_field_tag :non_striker_id, @non_striker.id %>
      <tr>
        <th colspan="8" align="center" style="font-size:x-large">This Over: 
          <% @over.balls.each do |b| %>
            &nbsp&nbsp&nbsp<%= b.get_over_summary %>
          <% end %>
        </th>
      </tr>
      <tr>
        <td colspan="8" align="left"><% 195.times do %>-<%end%></td>
      </tr>
      <tr>
        <th>Result</th>
        <td><%= select_tag 'result', options_for_select(get_result_master_list), onchange: 'populateRuns();', id: 'result'%></td>
        <th>Runs</th>
        <td><%= number_field_tag 'runs_scored', 1, min:0, max:6, id:'runs_scored'%></td>
        <th>Extra Type</th>
        <td><%= select_tag 'extra_type', options_for_select(get_extra_master_list), id:'extra_type', onchange: 'populateExtraRuns();' %></td>
        <th>Extra Runs</th>
        <td><%= number_field_tag 'extra_runs', id:'extra_runs' %></td>
      </tr>
      <tr>
        <th>Wicket Type</th>
        <td><%= select_tag 'wicket_type', options_for_select(get_wicket_master_list) %></td>
        <th>Batsman</th>
        <td><%= select_tag 'wicket_batsman', options_from_collection_for_select(@batsmen, "id", "get_full_name", @striker.id) %></td>
        <th>Partner</th>
        <td><%= select_tag 'wicket_partner', options_from_collection_for_select(@opponents, "id", "get_full_name", @striker.id), include_blank:true %></td>
        <td colspan="2" align="center"><%= submit_tag 'Submit' %>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to "Switch Strike", admin_inning_switch_strike_path(@inning), :class => 'myButton' %>
<%= link_to 'Back', admin_match_path(@inning.match), :class => 'myButton' %>

app/views/admin/innings/start_innings.html.erb
<table class="form-style-10">
	<h1 align="center">CHOOSE BOWLER AND BATSMEN</h1>
	<%= form_tag admin_inning_proceed_innings_path do %>
		<tr>
			<th>Select Batsmen</th>
			<td><%= select_tag 'batsman_1', options_from_collection_for_select(@batsmen, "id", "get_full_name", @active_batsmen.first.try(:id)), disabled: @active_batsmen.first.present? %></td>
			<td><%= select_tag 'batsman_2', options_from_collection_for_select(@batsmen, "id", "get_full_name", @active_batsmen.second.try(:id)), disabled: @active_batsmen.second.present? %></td>
		</tr>
		<tr>
			<th>Select Bowler</th>
			<td><%= select_tag 'bowler_id', options_from_collection_for_select(@bowlers, "id", "get_full_name", @active_bowler.try(:id)), disabled: @active_bowler.present? %></td>
			<td align="center"><%= submit_tag 'Submit' %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Back', admin_match_path(@inning.match), :class => 'myButton' %>