config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/users#index'
 
  resources :users
  resources :bid_logs
  namespace :admin do
    resources :users do
      get 'delete_avatar'
      get 'list_team_players'
      post 'close_bid'
    end

    resources :matches do
      collection do
        get 'points_table'
      end
    end

    resources :innings do
      get 'start_innings'
      post 'proceed_innings'
      post 'create_ball_details'
      post 'create_over'
      get 'switch_strike'
      get 'scoreboard'
    end
  end
  namespace :team_owner do
    resources :users do
      get 'list_team_players'
      get 'delete_avatar'
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :innings
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController

	def index
		@matches = Match.all
	end

	def show
		@match = Match.where(id: params[:id]).first
		@innings = @match.innings
	end

	def new
		@match = Match.new
		@teams = Team.pluck(:name, :id)
	end

	def create
		match = Match.create(name: params[:match][:name],
												team_1_id: params[:match][:team_1_id],
												team_2_id: params[:match][:team_2_id],
												status: 'NEW')
		Inning.create(team_id: params[:match][:team_1_id],
									opponent_id: params[:match][:team_2_id],
									match_id: match.id,
									runs_scored: 0,
									overs_played: 0.0,
									status: 'NEW')
		Inning.create(team_id: params[:match][:team_2_id],
									opponent_id: params[:match][:team_1_id],
									match_id: match.id,
									runs_scored: 0,
									overs_played: 0.0,
									status: 'NEW')
		redirect_to admin_match_path(match)
	end

	def points_table
		@teams = Team.all
		@teams = @teams.sort_by(&:calculate_net_run_rate).reverse
	end
end

app/views/admin/matches/index.html.erb
<h1 align="center">MATCHES HOME</h1>
<table class="flat-table flat-table-1" align="center" >
  <tr>
    <th align="center">Match</th>
    <th align="center">Team 1</th>
    <th align="center">Team 2</th>
    <th align="center">Status</th>
    <th align="center">Toss</th>
    <th align="center">Winner</th>
    <th colspan="4" align="center">Options</th>
  </tr>
  <% @matches.each do |match| %>
    <tr>
      <td><%= match.name %></td>
      <td align="center"><%= Team.where(id: match.team_1_id).first.name %></td>
      <td align="center"><%= Team.where(id: match.team_2_id).first.name %></td>
      <td align="center"><%= match.status %></td>
      <td align="center"><%= Team.where(id: match.toss_winner_id).first.try(:name) %></td>
      <td align="center"><%= Team.where(id: match.winner_id).first.try(:name) || '--' %></td>
      <td>&nbsp<%= link_to "Show Match Details", admin_match_path(match), :class => 'myButton' %></td>
    </tr>
  <% end %>
</table>
<div align="center">
  <%= link_to 'New Match', new_admin_match_path, data: { no_turbolink: true }, id:'myButton', :class => 'myButton' %>
  <%= link_to 'Points Table', points_table_admin_matches_path, data: { no_turbolink: true }, id:'myButton', :class => 'myButton' %>
  <%= link_to 'Back', admin_users_path, :class => 'myButton' %>
</div>

app/views/admin/matches/new.html.erb
<h1 align="center" >NEW MATCH</h1>
<%= form_for [:admin,@match] do |f| %>
  <table class="form-style-10"  >
	  <tr >
	    <td> <%= f.label :name %> </td>
	    <td> <%= f.text_field :name %></td>

	    <td> <%= f.label :team_1 %></td>
	    <td> <%= f.select(:team_1_id, @teams) %></td>
	 
	    <td> <%= f.label :team_2 %></td>
	    <td> <%= f.select(:team_2_id, @teams) %></td>
	  </tr>
	  <tr>
	    <td/><td/><td><%= f.submit %></td>
	  </tr>
	</table>
<% end %>

<%= link_to 'Back', admin_matches_path, :class => 'myButton' %>

app/views/admin/matches/points_table.html.erb
<h1 align="center">POINTS TABLE</h1>
<table class="flat-table flat-table-1" align="center" >
  <tr>
    <th>Team Name</th>
    <th>Matches</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>Net Run Rate</th>
  </tr>
  <% @teams.each do |team| %>
    <tr>
      <td><%= team.name %></td>
      <td><%= team.innings.count %></td>
      <td><%= Match.where(winner_id: team.id).count %></td>
      <td><%= team.matches.where(status:'COMPLETED').count - Match.where(winner_id: team.id).count %></td>
      <td><%= team.calculate_net_run_rate %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', admin_matches_path, :class => 'myButton' %>

app/views/admin/matches/show.html.erb
<table class="form-style-10">
  <h1 id="label" align="center"><%= @match.name %></h1>
  <tr>
    <td align="right" style="font-size:x-large"><strong><%= @innings.first.team.name %>: </strong></td>
    <td align="left" style="font-size:xx-large"><strong><%= @innings.first.runs_scored%>/<%= @innings.first.wickets.count %></strong></td>
    <td>
      <% if @innings.first.status == 'NEW' %>
        <%= link_to "Start Innings", admin_inning_start_innings_path(@innings.first), :class => 'myButton' %>
      <% elsif @innings.first.status == 'ONGOING' %>
        <%= link_to "Continue Innings", admin_inning_path(@innings.first), :class => 'myButton' %>
      <% end %>
      <% if ['ONGOING', 'COMPLETED'].include?(@innings.first.status) %>
        <%= link_to "Scoreboard", admin_inning_scoreboard_path(@innings.first), :class => 'myButton' %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td align="right" style="font-size:x-large"><strong><%= @innings.last.team.name %>: </strong></td>
    <td align="left" style="font-size:xx-large"><strong><%= @innings.last.runs_scored%>/<%= @innings.last.wickets.count %></strong></td>
    <td>
      <% if @innings.last.status == 'NEW' %>
        <%= link_to "Start Innings", admin_inning_start_innings_path(@innings.last), :class => 'myButton' %>
      <% elsif @innings.last.status == 'ONGOING' %>
        <%= link_to "Continue Innings", admin_inning_path(@innings.last), :class => 'myButton' %>
      <% end %>
      <% if ['ONGOING', 'COMPLETED'].include?(@innings.last.status) %>
        <%= link_to "Scoreboard", admin_inning_scoreboard_path(@innings.last), :class => 'myButton' %>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to 'Back', admin_matches_path, :class => 'myButton' %>