config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/users#index'
 
  resources :users
  resources :bid_logs
  namespace :admin do
    resources :users do
      get 'delete_avatar'
      get 'list_team_players'
      post 'close_bid'
    end

    resources :matches do
      collection do
        get 'points_table'
      end
    end

    resources :innings do
      get 'start_innings'
      post 'proceed_innings'
      post 'create_ball_details'
      post 'create_over'
      get 'switch_strike'
      get 'scoreboard'
    end
  end
  namespace :team_owner do
    resources :users do
      get 'list_team_players'
      get 'delete_avatar'
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/bid_log.rb
class BidLog < ApplicationRecord
  belongs_to :user
  scope :get_highest_bid, lambda { |id| where(player_id: id).order('amount DESC').first }
  after_create_commit { BidLogBroadcastJob.perform_later(self) }
  after_update_commit { BidLogBroadcastJob.perform_later(self) }
end

app/controllers/admin/bid_logs_controller.rb
class BidLogsController < ApplicationController
  # before_action :authenticate_user!
   respond_to :html, :js

  def index
    @bid_logs = BidLog.all
    @new_bid = current_user.bid_logs.build
  end

  def create
    @bid_log = current_user.bid_logs.build(bid_log_params)
    
    if @bid_log.save
      sync_new @bid_log
    end
    respond_to do |format|
      format.html { redirect_to user_path(@bid_log.player_id) }
      format.json { head :no_content }
    end
  end

  private

  def bid_log_params
    params.require(:bid_log).permit(:amount, :player_id)
  end
end
 

app/controllers/bid_logs_controller.rb
class BidLogsController < ApplicationController
  # before_action :authenticate_user!
   respond_to :html, :js

  def index
    @bid_logs = BidLog.all
    @new_bid = current_user.bid_logs.build
  end

  def create
    player = User.where(id: bid_log_params['player_id']).first
    if current_user.role.try(:name) == 'admin'
      player.sell_player
      @bid_log = BidLog.get_highest_bid(player.id)
      @bid_log.is_closed = true
    else
      @bid_log = current_user.bid_logs.build(bid_log_params)
      player.update_team_status
    end
      @bid_log.save
    respond_to do |format|
      if current_user.role.try(:name) == 'admin'
        format.html { redirect_to admin_user_path(@bid_log.player_id) }
      else
        format.html { redirect_to team_owner_user_path(@bid_log.player_id) }
      end
      format.json { head :no_content }
    end
  end

  private

  def bid_log_params
    params.require(:bid_log).permit(:amount, :player_id)
  end
end
 

app/controllers/team_owner/bid_logs_controller.rb
class BidLogsController < ApplicationController
  # before_action :authenticate_user!
   respond_to :html, :js

  def index
    @bid_logs = BidLog.all
    @new_bid = current_user.bid_logs.build
  end

  def create
    @bid_log = current_user.bid_logs.build(bid_log_params)
    
    if @bid_log.save
      sync_new @bid_log
    end
    respond_to do |format|
      format.html { redirect_to team_owner_user_path(@bid_log.player_id) }
      format.json { head :no_content }
    end
  end

  private

  def bid_log_params
    params.require(:bid_log).permit(:amount, :player_id)
  end
end

app/controllers/team_owner/users_controller.rb
class TeamOwner::UsersController < ApplicationController
	# load_and_authorize_resource except: [:create]
  def index
    @users = User.where(role_id: Role.get_user_role_id).order(:id)
  end

  def show
    @user = User.find(params[:id])
    @team = Team.get_team(current_user.id).first
    @next_user = User.where('id > ? AND role_id = ?', params[:id], Role.get_user_role_id).limit(1).first
    @purse_balance = @team.total_purse - @team.purse_spent
    @no_of_players = User.where(team_id: @team.id).count
    @male_players = User.where(team_id: @team.id, gender:'MALE').count
    @female_players = User.where(team_id: @team.id, gender:'FEMALE').count
    if @user.team_status == 'UNSOLD'
      @bid_log = BidLog.new
    else
      @bid_log = BidLog.where(player_id: @user.id).order('amount DESC').limit(1).first
    end
    @new_bid_log = BidLog.new
  end

  def list_team_players
    team_id = current_user.team_id
    @players = User.where(team_id: team_id, role_id:  Role.get_user_role_id)
  end
end

app/helpers/bid_logs_helper.rb
module BidLogsHelper
end

app/helpers/team_owner/users_helper.rb
module TeamOwner::UsersHelper
end

app/views/team_owner/bid_logs/_bid_log.html.erb
	<%= hidden_field_tag :bid_log_present, bid_log.amount.present? %>
	<%= hidden_field_tag :bid_closed, bid_log.is_closed.present? %>
	<script type="text/javascript">
		bidSummaries = document.getElementsByClassName('BidSummary');
		if(bidSummaries != null){
		// 	if(document.getElementById('bid_closed').value == 'true'){
		// 		// if(bidSummaries != null){
		// 			document.getElementsByClassName('BidSummary')[0].remove();
		// 			document.getElementsByClassName('BidSummary')[0].remove();
		// 		// }
		// 	// 	for(i=0; i<3; i++){
		// 	// 		document.getElementById('BidSummary').remove();
		// 	// 	}
		// 	}
		// 	if(bidSummaries != null){
		// 		for(i=0; i<bidSummaries.length; i++){
		// 			document.getElementsByClassName('BidSummary')[0].remove();
		// 			// document.getElementsByClassName('BidSummary')[0].remove();
		// 		}
		// 	}
		// }
		// else if(bidSummaries != null){
		// 	document.getElementsByClassName('BidSummary')[0].remove();
			for(i=0; bidSummaries[1] != null; i++){
				document.getElementsByClassName('BidSummary')[0].remove();
			}
		}
		if(document.getElementById('submit_button') != null){
			document.getElementById('submit_button').disabled = false;
		}
		if(document.getElementById('bid_closed').value == 'true'){
			document.getElementById('BidForm').hidden = true;
		}
	</script>
	<% if bid_log.amount.present? %>
		<div class="BidSummary">
			<% if bid_log.is_closed %>
				Sold To: <%= bid_log.user.try(:first_name) || '--' rescue nil%> for: <%= bid_log.amount || '--' rescue nil%> points!
			<% else %>
				<%= hidden_field_tag :current_bid_amount, bid_log.amount %>
				Current Bid:<br/><%= bid_log.amount || '--' rescue nil%><br/><br/>
				Current Bidder:<br/><%= bid_log.user.try(:first_name) || '--' rescue nil%>
			<% end %>
		</div>
	<% end %>

app/views/team_owner/bid_logs/_form.html.erb
<%= form_for(@bid_log) do |f| %>
  <% if @bid_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid_log.errors.count, "error") %> prohibited this bid_log from being saved:</h2>

      <ul>
      <% @bid_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_owner/bid_logs/edit.html.erb
<h1>Editing Bid Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid_log %> |
<%= link_to 'Back', bid_logs_path %>

app/views/team_owner/bid_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bid Logs</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bid_logs.each do |bid_log| %>
      <tr>
        <td><%= bid_log.amount %></td>
        <td><%= bid_log.user %></td>
        <td><%= link_to 'Show', bid_log %></td>
        <td><%= link_to 'Edit', edit_bid_log_path(bid_log) %></td>
        <td><%= link_to 'Destroy', bid_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid log', new_bid_log_path %>

app/views/team_owner/bid_logs/new.html.erb
<h1>New Bid Log</h1>

<%= render 'form' %>

<%= link_to 'Back', bid_logs_path %>

app/views/team_owner/bid_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @bid_log.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @bid_log.user %>
</p>

<%= link_to 'Edit', edit_bid_log_path(@bid_log) %> |
<%= link_to 'Back', bid_logs_path %>