config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin/users#index'
 
  resources :users
  resources :bid_logs
  namespace :admin do
    resources :users do
      get 'delete_avatar'
      get 'list_team_players'
      post 'close_bid'
    end

    resources :matches do
      collection do
        get 'points_table'
      end
    end

    resources :innings do
      get 'start_innings'
      post 'proceed_innings'
      post 'create_ball_details'
      post 'create_over'
      get 'switch_strike'
      get 'scoreboard'
    end
  end
  namespace :team_owner do
    resources :users do
      get 'list_team_players'
      get 'delete_avatar'
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :designation
  belongs_to :role
  belongs_to :team
  has_many :bid_logs
  mount_uploader :avatar, AvatarUploader
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/}
  validates :last_name, presence: true
  # validates :email, presence: true, uniqueness: true, format: {with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\z/}
  #validates :deactivated_on, absence: true, if: :is_active
  # validates :work_phone, format: {with: /\A(180\-)?[0-9]{3}(\-)?[0-9]{3}(\-)?[0-9]{4}\z/}
  before_save :set_default_values, :revert_locked_data
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  scope :active_users, -> {where("status='Active'")}
  scope :locked_users, -> {where("status='Locked'")}
  scope :created_before, ->(time) { where("created_at < ?", time).select(:first_name)}

  def revert_locked_data
    if self.status == "Active"
      self.deactivated_on = nil
      self.reason = nil
    end
  end
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end

  def set_default_values
    self.role_id ||= Role.find_by_name("user").try(:id)
    self.status ||= "Active"
  end
  def calculate_total_experience
    # self.previous_experience + ((Date.today-self.date_of_joining)/365).round(2)
  end

  def get_team_name
    team.try(:name)
  end

  def sell_player
    bid = BidLog.get_highest_bid(id)
    team = Team.where(owner_id: bid.user_id).first
    self.update_attributes(team_id: team.try(:id), team_status: 'SOLD', sold_points: bid.amount)
    team.purse_spent = team.purse_spent + bid.amount
    team.save
  end

  def update_team_status
    if team_status == 'UNSOLD'
      self.update_attributes(team_status: 'BIDDING')
    end
  end

  def get_full_name
    first_name + ' ' + middle_name + ' ' + last_name
  end

  def calculate_runs(inning_id)
    inning = Inning.where(id: inning_id).first
    record = Inning.select('SUM(balls.runs_scored) AS runs_sum,
                SUM(is_legitimate) AS balls_sum,
                SUM(result = "4 Runs") AS fours_sum,
                SUM(result = "6 Runs") AS sixes_sum')
            .joins('INNER JOIN overs ON overs.inning_id = innings.id
                INNER JOIN balls ON balls.over_id = overs.id')
            .where('balls.batsman_id = ? AND innings.id = ?', self.id, inning_id).first
    [record.runs_sum, record.balls_sum, record.fours_sum, record.sixes_sum]
  end

  def get_wicket_info(inning_id, balls_played)
    wicket = Wicket.where(inning_id: inning_id, batsman_id: self.id).first
    if wicket.present?
      bowler = User.where(id: wicket.bowler_id).first.get_full_name
      partner = User.where(id: wicket.wicket_partner_id).first.try(:get_full_name)
      case wicket.wicket_type
      when 'Bowled'
        "b #{bowler}"
      when 'Caught'
        "c #{partner} b #{bowler}"
      when 'LBW'
        "LBW #{bowler}"
      when 'Stumped'
        "st #{partner} b #{bowler}"
      when 'Run Out'
        "runout(#{partner})"
      when 'Hit Wicket'
        "hitwicket"
      when 'Hit Out'
        "hitout b #{bowler}"
      end
    else
      if balls_played.blank?
        "--"
      else
        "not out"
      end
    end
  end

  def crease_arrival_order(inning_id)
    arrival_time = Ball.joins(:over)
      .where('balls.batsman_id = ? AND overs.inning_id = ?', self.id, inning_id)
      .order('balls.created_at')
      .limit(1)
      .first.try(:created_at)
    arrival_time || Time.now
  end

  def get_bowling_details(inning_id)
    inning = Inning.where(id: inning_id).first
    overs = inning.overs.where(bowler_id: self.id)
    runs = Ball.select('SUM(runs_scored) AS runs').where(over_id: overs.map(&:id)).first
    ball_count = overs.map(&:legitimate_balls).flatten.count
    wickets = inning.wickets.where(bowler_id: self.id, wicket_type:['Bowled','Caught','LBW','Stumped','Hit Wicket','Hit Out']).count
    [(ball_count.to_f / 6).round(2), wickets, runs.runs]
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource except: [:create]
  def index
    @users = User.where(role_id: Role.get_user_role_id).order(:id)
  end

  def new
    @user = User.new
    get_designation_and_role_data
  end

  def create
	  @user = User.new(user_params)
    @user.team_status = 'UNSOLD'
    if @user.save
      if (params[:user][:avatar].present? && params[:crop])
        render :crop
      else
        redirect_to admin_user_path(@user)
      end
  	else
  		get_designation_and_role_data
   		render 'new'
  	end
  end

  def show
    @user = User.where(id: params[:id]).first
    @teams = Team.get_team_stats
    @next_user = User.where('id > ? AND role_id = ?', params[:id], Role.get_user_role_id).limit(1).first
    if @user.team_status == 'UNSOLD'
      @bid_log = BidLog.new
    else
      @bid_log = BidLog.where(player_id: @user.id).order('amount DESC').limit(1).first
    end
    @new_bid_log = BidLog.new(player_id: @user.id, amount:@bid_log.amount)
  end
  
  def edit
    @user = User.find(params[:id])
    get_designation_and_role_data
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if (params[:user][:avatar].present? && params[:crop])
        render :crop
      else
        redirect_to admin_user_path(@user)
      end
    else
      get_designation_and_role_data
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def close_bid
    #to_be_written
  end

  def list_team_players
    @team_list = Team.joins(:users).select('teams.name, GROUP_CONCAT(CONCAT(users.first_name, users.last_name)) AS players').group('teams.id')
  end
  
  private
 	def user_params
    params.require(:user).permit(:first_name,
      :middle_name, :last_name, :email, :login_id, :password, :password_confirmation,
      :employee_id, :date_of_birth, :gender, :time_zone, :designation_id, :date_of_joining,
      :education, :comments, :role_id, :status, :deactivated_on, :reason, :previous_experience,
      :work_phone, :avatar, :remove_avatar, :crop_x, :crop_y, :crop_w, :crop_h, :team_status)
 	end

  def get_designation_and_role_data
    @designations=Designation.pluck(:designation_name, :id)
    @roles = Role.pluck(:name, :id)
  end
end

app/controllers/team_owner/users_controller.rb
class TeamOwner::UsersController < ApplicationController
	# load_and_authorize_resource except: [:create]
  def index
    @users = User.where(role_id: Role.get_user_role_id).order(:id)
  end

  def show
    @user = User.find(params[:id])
    @team = Team.get_team(current_user.id).first
    @next_user = User.where('id > ? AND role_id = ?', params[:id], Role.get_user_role_id).limit(1).first
    @purse_balance = @team.total_purse - @team.purse_spent
    @no_of_players = User.where(team_id: @team.id).count
    @male_players = User.where(team_id: @team.id, gender:'MALE').count
    @female_players = User.where(team_id: @team.id, gender:'FEMALE').count
    if @user.team_status == 'UNSOLD'
      @bid_log = BidLog.new
    else
      @bid_log = BidLog.where(player_id: @user.id).order('amount DESC').limit(1).first
    end
    @new_bid_log = BidLog.new
  end

  def list_team_players
    team_id = current_user.team_id
    @players = User.where(team_id: team_id, role_id:  Role.get_user_role_id)
  end
end

app/controllers/users/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @user = User.new(user_params)
  #   super
  #   redirect_to @user
  # end
  # def after_sign_in_path_for(resource)
  #   @user = User.find(params[:id])
  #   p "Entered after sign in path........................................"
  #   if @user.status=="Active"
  #     p "Entered condition"
  #     admin_users_path
  #   else
  #     reset_session
  #   end
  # end
  # def after_sign_up_path_for(resource)
  #   user_path(resource)
  # end
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  # private
  # def user_params
  #   params.require(:user).permit(:first_name, :middle_name, :last_name, :email, :login_id, :password, :password_confirmation, :employee_id, :date_of_birth, :gender, :time_zone, :designation_id, :date_of_joining, :education, :comments, :work_phone)
  # end
end

app/controllers/users/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #    super
  #    redirect_to @user
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   # load_and_authorize_resource
  # def index
  # 	@users = User.all
  #   @designations=Designation.all.map{|d| [d.designation_name, d.id]}
  # end

  # def new
  # 	@user = User.new
  #   @designations=Designation.all.map{|d| [d.designation_name, d.id]}
  # end
  # def create
	 #  @user = User.new(user_params)
 	#   if @user.save
  #   	redirect_to @user
  # 	else
  #     @designations=Designation.all.map{|d| [d.designation_name, d.id]}

  #  		render 'new'

  # 	end
  # end
  def show
    @user = User.find(params[:id])
    if @user.team_status == 'UNSOLD'
      @bid_log = BidLog.new
    else
      @bid_log = BidLog.last
    end
    @total_experience = @user.calculate_total_experience
  end

  def edit
    @user = User.find(params[:id])
    @designations = Designation.pluck(:designation_name, :id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy
  #   redirect_to users_path
  # end

  private
 	def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :email, :login_id,  :employee_id, :date_of_birth, :gender, :time_zone, :designation_id, :date_of_joining, :education, :comments, :previous_experience, :work_phone, :avatar, :remove_avatar, :crop_x, :crop_y, :crop_w, :crop_h, :team_status)
 	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/team_owner/users_helper.rb
module TeamOwner::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/crop.html.erb
<h1> Crop Avatar </h1>
<%= image_tag @user.avatar_url(:large), id: "cropbox" %>
<%= form_for [:admin,@user] do |f| %>
	<% %w[x y w h].each do |attribute| %>
		<%= f.hidden_field "crop_#{attribute}" %>
	<% end %>
	<div class = "actions">
		<%= f.submit "Crop" %>
	</div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for [:admin,@user] do |f| %>
  <%= render :partial =>'common/form', :locals=> {:f=>f}%>
<% end %>
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1 align="center">RCL AUCTION HOME</h1>
<table class="flat-table flat-table-1" align="center" >
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Team</th>
    <th>Base Points</th>
    <th>Sold Points</th>
    <th colspan="4" align="center">Options</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td align="left"><%= user.middle_name %> <%= user.last_name %></td>
      <td align="center"><%= user.get_team_name || '--' %></td>
      <td align="center"><%= user.base_points %></td>
      <td align="center"><%= user.sold_points %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user), data: { no_turbolink: true }, :class => 'myButton' %></td>
      <td>&nbsp<%= link_to 'Delete', admin_user_path(user), confirm: 'Are you sure?',
              :method => :delete, :class => 'myButton' %></td>
      <td>&nbsp<%= link_to "Show Full Details", admin_user_path(user), :class => 'myButton' %></td>
      <% if user.team_status == 'SOLD' %>
        <th><div class ='myButtonRed'>SOLD!</div></th>
      <% else %>
        <td align="center">&nbsp<%= link_to "BUY", admin_user_path(user), :class => 'myButtonGreen' %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<div align="center">
  <%= link_to 'New User', new_admin_user_path, data: { no_turbolink: true }, id:'myButton', :class => 'myButton' %>
</div>

app/views/admin/users/list_team_players.html.erb
<h1 align="center">RCL AUCTION HOME</h1>
<% @team_list.each do |team| %>
  <table class="flat-table flat-table-1" align="center" >
    <tr>
      <th align="center"><%= team.name %></th>
    </tr>
    <% team.players.split(',').each do |player| %>
      <tr>
        <td align="center"><%= player %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/admin/users/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<h1 align="center" >NEW USER</h1>
<%= form_for [:admin,@user] do |f| %>
  <%= render :partial =>'common/form', :locals=> {:f=>f}%>
<% end %>


<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<table class="form-style-10">
    <%= render :partial =>'common/details'%>
    <th align="left" id = "bid_partial">
       <%= render  @bid_log %>
    </th>
  <tr>
    <td>
      <div id='BidForm'>
        <%= form_for @new_bid_log, html: { id: 'admin-message-form' }  do |f| %>
          <%= f.hidden_field :player_id, value: @user.id %>
          <%= f.submit 'Close Bid', id: 'submit_button'%>
        <% end %>
      </div>
    </td>
  </tr>
</table>
<div align="center" style="padding-left:800px">
   <%= link_to "Players Bought",admin_user_list_team_players_path(@user), :class => 'myButton' %>
	<% if @next_user.present? %>
    <a href="<%= admin_users_path %>" class='myButton'>Back</a>
		<%= link_to "Next Player", admin_user_path(@next_user), :class => 'myButton' %>
	<% end %>
</div>
<footer style="margin-top:100px; padding-left:200px; bottom:0px; position:fixed;">
  <table class='flat-table flat-table-1'>
    <tr>
      <% @teams.each_with_index do |team, i| %>
        <td/><th><%=team.name%></th><td>Balance: <%=team.total_purse - team.purse_spent%><br/>Players Bought:<%=team.player_count%>
        </td><td/>
      <% end %>
    </tr>
  </table>
</footer>
<script type="text/javascript">
  if(document.getElementById('team_status').value != 'BIDDING'){
    document.getElementById('submit_button').disabled = true;
  }
</script>